require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "vendor/**/*"
    - "node_modules/**/*"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/**/*"

Rails/Output:
  Exclude:
    - "config/initializers/prometheus.rb"

Rails/ThreeStateBooleanColumn:
  Exclude:
    - "db/migrate/**/*"

RSpec/MultipleExpectations:
  Max: 3
